### ISSUE TITLE
Collaboration suggestion

### ISSUE THREAD

**Issue by neokitten** [aurxdev0/aurx-core#2]
Hello, Mx. aurxdev0!

We saw your project and we would definitely like to collaborate with you!

**Who we are?** We are a funky cloud computing company targeted at small and middle-range companies in the US and Europe. Right now, we are trying to create a product that will allow our customers to make, share and run a virtual (Ubuntu/Fedora/Arch Linux-agnostic) Linux-based desktop environments, located in our cloud. I feel like we share a lot of interests on this particular subject.

Please, feel free contact us at <contact@floppa.space> for more information.

---
Sincerely yours, Floppa Solutions Inc.
+1 212-527-4554
211 East 43rd Street, New York City, NY.

**Comment by aurxdev0** [comment]
Yeah, I damn well believe you. You're from Russia, but you pretend to be foreigners. Okay, I'll cooperate, but know not to be an impostor.
Regards. 
Mr. aurxdev

**Comment by aurxdev0** [comment]
Well, if you're going to help develop the project, go for it! I'd be happy to. I have debian now, but maybe in the near future I will install Arch linux on the host.

**Comment by aurxdev0** [comment]
No! I will not cooperate. I'm not ready for this kind of business. Period!

**Comment by aurxdev0** [comment]
Okay... but why would I need that information

**Comment by aurxdev0** [comment]
I don't know what to say. I'm sorry, but you're on the blacklist.

**Comment by aurxdev0** [comment]
I don't know why. I just feel like there's something wrong.
